### ISSUE TITLE
Add test dependencies

### ISSUE THREAD

**Issue by darkwing** [mozilla-services/mozphab#8]
We'll need to add the following to allow testing within the phabricator container:

- bash 
- make
- g++

**Comment by mars-f** [comment]
The container is focused on serving production web traffic, and it sounds like adding the ability to test within the container breaks the goal of having containers have a single responsibility.  And bringing in the whole C++ toolchain just to run that new responsibility doesn't sound right.

Could we install the dependencies in a sidecar container just for testing, and use volumes_from to mount the sourcecode?  Or perhaps a derivative container for testing using a `FROM mozilla/mozphab` statement?

**Comment by darkwing** [comment]
At the meeting today, @ckolos said we should create a separate repo with a `BUILDON` directive, so I'll close this.
